apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"example-webhook"},"name":"example-webhook","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"example-webhook"}},"template":{"metadata":{"labels":{"app":"example-webhook"}},"spec":{"containers":[{"image":"10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/enrich-cr-webhook:test","imagePullPolicy":"Always","name":"server","ports":[{"containerPort":8443,"name":"tls"},{"containerPort":80,"name":"metrics"}],"volumeMounts":[{"mountPath":"/etc/webhook/certs/","name":"example-webhook-tls-certs","readOnly":true},{"mountPath":"/etc/rules","name":"config-volume"}]}],"nodeSelector":{"kubernetes.io/os":"linux"},"securityContext":{"runAsNonRoot":true,"runAsUser":1234},"serviceAccountName":"example-webhook","volumes":[{"name":"example-webhook-tls-certs","secret":{"secretName":"example-webhook-tls"}},{"configMap":{"name":"enrich-cr-config"},"name":"config-volume"}]}}}}
  creationTimestamp: "2024-02-21T05:46:50Z"
  labels:
    app: example-webhook
  name: example-webhook
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: example-webhook
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: example-webhook
    spec:
      containers:
      - image: 10.108.30.10:5000/atom-docker/cn2/bazel-build/dev/x86_64/enrich-cr-webhook:test
        imagePullPolicy: Always
        name: server
        ports:
        - containerPort: 8443
          name: tls
          protocol: TCP
        - containerPort: 80
          name: metrics
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/webhook/certs/
          name: example-webhook-tls-certs
          readOnly: true
        - mountPath: /etc/rules
          name: config-volume
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        runAsUser: 1234
      serviceAccount: example-webhook
      serviceAccountName: example-webhook
      terminationGracePeriodSeconds: 30
      volumes:
      - name: example-webhook-tls-certs
        secret:
          defaultMode: 420
          secretName: example-webhook-tls
      - configMap:
          defaultMode: 420
          name: enrich-cr-config
        name: config-volume
